### ISSUE TITLE
Don't use block height as a primary key

### ISSUE THREAD

**Issue by gtank** [zcash-hackworks/lightwalletd#32] opened 2019-04-16 19:28 UTC
It's likely causing failures during reorgs or other transient failures that result in a rebroadcast. Found by @ianamunoz and @gmale.

https://github.com/zcash-hackworks/lightwalletd/blob/master/storage/sqlite3.go#L30

**Comment by gmale** [comment] 2019-04-23 17:02
This basically boils down to "implement re-orgs" which is a feature we knowingly punted on, as a trade-off.

**Comment by gmale** [comment] 2019-04-24 01:37
Related to and possibly a duplicate of #31

**Comment by mms710** [comment] 2019-04-24 20:11
Relates to https://github.com/zcash/zcash-android-wallet-sdk/issues/23

**Comment by mdr0id** [comment] 2019-09-16 14:51
No longer relevant due to updates to mentioned topics

**Closed by mdr0id** 2019-09-16 14:51 UTC
